In [1]:
import numpy as np
from scipy.stats import multivariate_normal
from matplotlib import pyplot as plt
from copy import copy
from datetime import datetime, timedelta

from stonesoup.functions import gm_reduce_single

from stonesoup.predictor.kalman import KalmanPredictor
from stonesoup.updater.kalman import KalmanUpdater
from stonesoup.predictor.imm import IMMPredictor
from stonesoup.updater.imm import IMMUpdater
from stonesoup.models.transition.linear import ConstantVelocity, \
    CombinedLinearGaussianTransitionModel, LinearGaussianTimeInvariantTransitionModel

from stonesoup.models.measurement.linear import LinearGaussian

from stonesoup.types.state import GaussianState
from stonesoup.types.hypothesis import SingleHypothesis
from stonesoup.types.detection import Detection
from stonesoup.types.state import StateVector, CovarianceMatrix, \
    GaussianMixtureState, WeightedGaussianState
from stonesoup.types.track import Track

from stonesoup.simulator.simple import SingleTargetGroundTruthSimulator

from matplotlib.patches import Ellipse


In [2]:
from emgpb2.states import Gaussian as EMGPB2Gaussian
from emgpb2.states import GMM as EMGPB2GMM
from emgpb2.states import GMMSequence as EMGPB2GMMSequence
from emgpb2.models import LinearModel as EMGPB2LinearModel
from emgpb2.models import ConstantVelocity as EMGPB2ConstantVelocity
from emgpb2.EM import SKFEstimator

Simulate groundtruth and detections

In [3]:
# dimension of state vector and observation
state_dim = 4
obs_dim = 2

# define transition models
gt_transition_model_1 = CombinedLinearGaussianTransitionModel(
                        (ConstantVelocity(1.0),
                         ConstantVelocity(1.0)))
gt_transition_model_2 = CombinedLinearGaussianTransitionModel(
                        (ConstantVelocity(8.0),
                         ConstantVelocity(8.0)))

# define measurement models
mesurement_noise_1 = np.diag([0.5 ** 2, 0.5 ** 2])
measurement_model_1 = LinearGaussian(ndim_state=4, mapping=[0, 2], noise_covar=mesurement_noise_1)
mesurement_noise_2 = np.diag([0.25 ** 2, 0.25 ** 2])
measurement_model_2 = LinearGaussian(ndim_state=4, mapping=[0, 2], noise_covar=mesurement_noise_2)

# iteration numbers of two models
iter_model_1 = 220
iter_model_2 = 180

# generate groundtruth
gt_track = []
gt_time = []
timestamp_init = datetime.now()

# model 1
state_init_1 = GaussianState(StateVector(np.zeros((state_dim, 1))),
                           CovarianceMatrix(np.zeros((state_dim, state_dim))),
                           timestamp=timestamp_init)
gt_generator_1 = SingleTargetGroundTruthSimulator(gt_transition_model_1, state_init_1, number_steps=iter_model_1)
for time, gnd_paths in gt_generator_1.groundtruth_paths_gen():
    gnd_path = gnd_paths.pop()
    gt_track.append(gnd_path.state)
    gt_time.append(time)

# model 2
state_init_2 = GaussianState(gt_track[-1].state_vector, 
                             CovarianceMatrix(np.zeros((state_dim, state_dim))), 
                             timestamp=gt_time[-1])
gt_generator_2 = SingleTargetGroundTruthSimulator(gt_transition_model_2, state_init_2, number_steps=iter_model_2)
for time, gnd_paths in gt_generator_2.groundtruth_paths_gen():
    gnd_path = gnd_paths.pop()
    gt_track.append(gnd_path.state)
    gt_time.append(time)

# generate detections (adding noise)
# model 1
detection_track = []
for i in range(iter_model_1):
    m_ = Detection(measurement_model_1.function(gt_track[i].state_vector, measurement_model_1.rvs(1)), gt_time[i])
    detection_track.append(m_)
# model 2
for i in range(iter_model_2):
    ii = i + iter_model_1
    m_ = Detection(measurement_model_2.function(gt_track[ii].state_vector, measurement_model_2.rvs(1)), gt_time[ii])
    detection_track.append(m_)

Filter model. Testing by correct parameters.

In [4]:
# model transition probability
model_transition_matrix = np.array([[0.5, 0.5],
                                    [0.5, 0.5]])

# define two kalman predictors. re-use the groundtruth transition model.
predictor_1 = KalmanPredictor(gt_transition_model_1)
predictor_2 = KalmanPredictor(gt_transition_model_2)

# define IMM predictor
imm_predictor = IMMPredictor([predictor_1, predictor_2],
                             model_transition_matrix)

# define two kalman updaters. re-use the groundtruth measurement model.
updater_1 = KalmanUpdater(measurement_model_1)
updater_2 = KalmanUpdater(measurement_model_2)

# define IMM updater
imm_updater = IMMUpdater([updater_1, updater_2], model_transition_matrix)

# initialise state for kalman filter 1
ft_state_init_1 = WeightedGaussianState(StateVector(np.zeros((state_dim, 1))),
                                      CovarianceMatrix(np.eye(state_dim) * 1.0),
                                      timestamp=timestamp_init,
                                      weight=0.5)

# initialise state for kalman filter 2
ft_state_init_2 = WeightedGaussianState(StateVector(np.zeros((state_dim, 1))),
                                      CovarianceMatrix(np.eye(state_dim) * 1.0),
                                      timestamp=timestamp_init,
                                      weight=0.5)

# define Gaussian Mixture model for initial state
prior = GaussianMixtureState([ft_state_init_1, ft_state_init_2])
track = Track([copy(prior)])

# tracking
track_error = []
for i in range(1, len(detection_track)-1):
    # measurement
    measurement = detection_track[i]
    # State prediction
    prediction = imm_predictor.predict(track.state, timestamp=gt_time[i])
    # Measurement prediction
    meas_prediction = imm_updater.predict_measurement(prediction)
    # Association
    hyp = SingleHypothesis(prediction, measurement)
    # State update
    prior = imm_updater.update(hyp)
    track.append(prior)
    track_error.append(measurement_model_1.function(track[i].state_vector, np.zeros((obs_dim, 1)))
                       - measurement_model_1.function(gt_track[i].state_vector, np.zeros((obs_dim, 1))))

track_error = np.asarray(track_error)
track_error = np.squeeze(track_error)
rmse_tmp = []
for track_error_ in track_error:
    rmse_tmp.append(track_error_ @ track_error_.T)
rmse = np.sqrt(np.mean(np.array(rmse_tmp)))
print("RMSE: " + str(rmse))

RMSE: 0.5758576894330582


Gussing some IMM paramters.

In [5]:
init_P = [5.0, 5.0]
q = [1.0, 15.0]
r = [3.0, 3.0]

Filter model. Testing by guessing IMM parameters.

In [6]:
# define model transition probability
ft_model_transition_matrix = np.array([[0.5, 0.5],
                                       [0.5, 0.5]])
# define transition model 1 using guessed parameter
ft_transition_model_1 = CombinedLinearGaussianTransitionModel(
                        (ConstantVelocity(q[0]),
                         ConstantVelocity(q[0])))
# define transition model 2 using guessed parameter
ft_transition_model_2 = CombinedLinearGaussianTransitionModel(
                        (ConstantVelocity(q[1]),
                         ConstantVelocity(q[1])))

# define measurement model. use same measurement model for two Kalman filters.
ft_measurement_noise = np.diag([r[0] ** 2, r[0] ** 2])
ft_measurement_model = LinearGaussian(ndim_state=4, mapping=[0, 2],
                                   noise_covar=ft_measurement_noise)

# define two kalman updaters.
ft_predictor_1 = KalmanPredictor(ft_transition_model_1)
ft_predictor_2 = KalmanPredictor(ft_transition_model_2)

# define IMM predictor
ft_imm_predictor = IMMPredictor([ft_predictor_1, ft_predictor_2], ft_model_transition_matrix)

# define IMM updater. use same measurement model for two Kalman filters.
ft_updater = KalmanUpdater(ft_measurement_model)
ft_imm_updater = IMMUpdater([copy(ft_updater), copy(ft_updater)], ft_model_transition_matrix)

# define Gaussian Mixture model for initial state. We used the same initial state as previous filter.
prior = GaussianMixtureState([ft_state_init_1, ft_state_init_2])
track = Track([copy(prior)])
track_error = []

for i in range(1, len(detection_track)-1):
    # measurement
    measurement = detection_track[i]
    # State prediction
    prediction = ft_imm_predictor.predict(track.state, timestamp=gt_time[i])
    # Measurement prediction
    meas_prediction = ft_imm_updater.predict_measurement(prediction)
    # Association
    hyp = SingleHypothesis(prediction, measurement)
    # State update
    prior = ft_imm_updater.update(hyp)
    track.append(prior)
    track_error.append(ft_measurement_model.function(track[i].state_vector, np.zeros((2,1))) - ft_measurement_model.function(gt_track[i].state_vector, np.zeros((2,1))))

track_error = np.asarray(track_error)
track_error = np.squeeze(track_error)
rmse_tmp = []
for track_error_ in track_error:
    rmse_tmp.append(track_error_ @ track_error_.T)
rmse = np.sqrt(np.mean(np.array(rmse_tmp)))
print("RMSE: " + str(rmse))

RMSE: 0.9833021174196005


Run EMGPB2 to estimate IMM parameters.

In [7]:
num_of_models = len(q)
gaussian_models = []
for i in range(num_of_models):
    gaussian_models.append(EMGPB2Gaussian(np.zeros([state_dim, 1]), (init_P[i] ** 2) * np.eye(state_dim)))
initial_gmm_state = EMGPB2GMM(gaussian_models)
# measurement sequence
detection_track_EMGPB2 = [ele.state_vector for ele in detection_track]
gmmsequence = EMGPB2GMMSequence(np.float64(detection_track_EMGPB2), initial_gmm_state)
dataset = [gmmsequence]
# Initial models. use guessed parameters.
constantvelocity_models = []
for i in range(num_of_models):
    constantvelocity_models.append(EMGPB2ConstantVelocity(dt=1.0, q=q[i], r=r[i], 
                                                          state_dim=state_dim, obs_dim=obs_dim, mode='diag'))

# Switching matrix probability
Z = np.ones((2, 2)) / 2

models_all, Z_all, dataset, LLs = SKFEstimator.EM(dataset, constantvelocity_models, Z,
                                                 max_iters=300, threshold=1e-8, learn_H=True, learn_R=True,
                                                 learn_A=True, learn_Q=True, learn_init_state=False, learn_Z=True,
                                                 diagonal_Q=False, wishart_prior=False)


new_models = new_models_all[-1]

# new_models[0].Q = (new_models[0].Q + new_models[0].Q.T)/2
# new_models[1].Q = (new_models[1].Q + new_models[1].Q.T)/2
# new_models[0].R = (new_models[0].R + new_models[0].R.T)/2
# new_models[1].R = (new_models[1].R + new_models[1].R.T)/2

-2380.5209185206613
model -- 0 new_A: 
[[ 1.00044646e+00  9.40075465e-01  5.82323162e-04 -4.12918953e-02]
 [ 4.84635700e-04  9.32694996e-01  7.25141611e-04 -5.37382233e-02]
 [-2.42713806e-04 -2.55857204e-02  1.00027105e+00  9.40324811e-01]
 [-3.32891918e-04 -2.35971236e-02  2.15130062e-04  9.40613626e-01]]
model -- 1 new_A: 
[[ 1.00037163e+00  9.32914882e-01  6.29114550e-04 -5.06320099e-02]
 [ 5.20666762e-04  9.21139879e-01  8.41508979e-04 -6.33384714e-02]
 [-2.38490326e-04 -2.53300626e-02  1.00023558e+00  9.44643407e-01]
 [-3.35806202e-04 -2.62415342e-02  2.14184530e-04  9.39819418e-01]]
model -- 0 new_Q: 
[[ 5.6451178   4.71771691 -0.13697146 -0.1299568 ]
 [ 4.71771691  7.80075158 -0.14251053 -0.13491509]
 [-0.13697146 -0.14251053  5.4364837   4.47365755]
 [-0.1299568  -0.13491509  4.47365755  7.35015079]]
model -- 1 new_Q: 
[[ 6.74396534  5.78559269 -0.31646008 -0.31017165]
 [ 5.78559269  9.72658212 -0.2926058  -0.31683999]
 [-0.31646009 -0.2926058   6.49177897  5.57814419]
 [-0.310

-1764.200233543218
model -- 0 new_A: 
[[ 1.00044517e+00  9.37979969e-01  6.02148290e-04 -4.30800590e-02]
 [ 1.80499046e-04  9.68489493e-01  4.44780393e-04 -3.74575161e-02]
 [-2.52775527e-04 -2.56323891e-02  1.00026901e+00  9.39517933e-01]
 [-2.71163147e-04 -1.85018894e-03 -5.15415903e-05  9.84002763e-01]]
model -- 1 new_A: 
[[ 1.00044485e+00  9.37984322e-01  6.02070219e-04 -4.30936670e-02]
 [ 1.80204827e-04  9.68494936e-01  4.44695290e-04 -3.74680069e-02]
 [-2.52686814e-04 -2.56304819e-02  1.00026897e+00  9.39529495e-01]
 [-2.71093193e-04 -1.85001639e-03 -5.15703973e-05  9.84012250e-01]]
model -- 0 new_Q: 
[[ 2.23953833  2.03978684 -0.03392995 -0.02062039]
 [ 2.03978771  3.91282267  0.09894373  0.14173757]
 [-0.03390958  0.09893128  1.99001196  1.77063165]
 [-0.02063319  0.14167545  1.7706323   3.40130433]]
model -- 1 new_Q: 
[[ 2.23962547  2.03979137 -0.03401312 -0.02067698]
 [ 2.03979224  3.91281872  0.09890885  0.14169623]
 [-0.03399274  0.0988964   1.99011308  1.77072883]
 [-0.0206

-1708.9577955144189
model -- 0 new_A: 
[[ 1.00044515e+00  9.38235850e-01  6.00375703e-04 -4.28010125e-02]
 [ 1.81614422e-04  9.68312626e-01  4.47751805e-04 -3.77359466e-02]
 [-2.50703480e-04 -2.57212277e-02  1.00027095e+00  9.39456970e-01]
 [-2.72306462e-04 -1.14551198e-03 -5.61956188e-05  9.84655056e-01]]
model -- 1 new_A: 
[[ 1.00044508e+00  9.38236440e-01  6.00363962e-04 -4.28041749e-02]
 [ 1.81556842e-04  9.68313390e-01  4.47739395e-04 -3.77386953e-02]
 [-2.50675999e-04 -2.57211071e-02  1.00027095e+00  9.39459420e-01]
 [-2.72282271e-04 -1.14569524e-03 -5.61974785e-05  9.84657263e-01]]
model -- 0 new_Q: 
[[ 1.79084766  2.01597967 -0.027165   -0.04606092]
 [ 2.0159796   3.96232682  0.13568165  0.14461978]
 [-0.02706225  0.13573152  1.54596123  1.70641253]
 [-0.04600844  0.14470454  1.70641283  3.36186386]]
model -- 1 new_Q: 
[[ 1.7908632   2.01597731 -0.02718262 -0.04607373]
 [ 2.01597724  3.96232176  0.13567353  0.14460729]
 [-0.02707987  0.13572339  1.54598009  1.70643153]
 [-0.046

-1703.3910982605607
model -- 0 new_A: 
[[ 1.00044803e+00  9.37894855e-01  6.03438573e-04 -4.29916989e-02]
 [ 1.97676566e-04  9.66196669e-01  4.66185409e-04 -3.90219426e-02]
 [-2.50027865e-04 -2.59524136e-02  1.00027399e+00  9.39095776e-01]
 [-2.74461417e-04 -2.08370302e-03 -4.38443966e-05  9.82734215e-01]]
model -- 1 new_A: 
[[ 1.00044800e+00  9.37895151e-01  6.03432761e-04 -4.29933281e-02]
 [ 1.97646107e-04  9.66197049e-01  4.66179222e-04 -3.90234672e-02]
 [-2.50012928e-04 -2.59523938e-02  1.00027399e+00  9.39097003e-01]
 [-2.74447498e-04 -2.08382243e-03 -4.38446718e-05  9.82735377e-01]]
model -- 0 new_Q: 
[[ 1.74774126  2.13538881 -0.02354036 -0.04727658]
 [ 2.13538814  4.22026144  0.15293134  0.16049984]
 [-0.02342896  0.152994    1.50534921  1.80621853]
 [-0.04721048  0.1606212   1.80621893  3.57658026]]
model -- 1 new_Q: 
[[ 1.74774682  2.13538571 -0.02354811 -0.04728235]
 [ 2.13538504  4.2202564   0.15292786  0.16049362]
 [-0.02343669  0.15299052  1.50535771  1.80622746]
 [-0.047

-1702.801037965723
model -- 0 new_A: 
[[ 1.00045028e+00  9.37608687e-01  6.05932891e-04 -4.31593808e-02]
 [ 2.04743543e-04  9.65250265e-01  4.74423464e-04 -3.96075155e-02]
 [-2.50006110e-04 -2.61192625e-02  1.00027607e+00  9.38805358e-01]
 [-2.74811814e-04 -2.59613671e-03 -3.76278350e-05  9.81823529e-01]]
model -- 1 new_A: 
[[ 1.00045026e+00  9.37608866e-01  6.05929447e-04 -4.31603133e-02]
 [ 2.04725400e-04  9.65250496e-01  4.74419729e-04 -3.96084150e-02]
 [-2.49997535e-04 -2.61192528e-02  1.00027607e+00  9.38806050e-01]
 [-2.74803698e-04 -2.59620255e-03 -3.76279069e-05  9.81824194e-01]]
model -- 0 new_Q: 
[[ 1.74543048  2.18907194 -0.02169785 -0.04198927]
 [ 2.18907111  4.33454167  0.16052657  0.17380914]
 [-0.02159246  0.16058714  1.50409139  1.85255472]
 [-0.04192529  0.17392749  1.85255522  3.6734982 ]]
model -- 1 new_Q: 
[[ 1.74543289  2.18906946 -0.0217018  -0.04199218]
 [ 2.18906863  4.33453787  0.16052496  0.17380594]
 [-0.02159641  0.16058553  1.50409596  1.85255958]
 [-0.0419

-1702.7475280098586
model -- 0 new_A: 
[[ 1.00045181e+00  9.37414427e-01  6.07594227e-04 -4.32684695e-02]
 [ 2.07214031e-04  9.64914130e-01  4.77361912e-04 -3.98203991e-02]
 [-2.50187161e-04 -2.62230094e-02  1.00027735e+00  9.38607858e-01]
 [-2.74699417e-04 -2.80724667e-03 -3.51923156e-05  9.81486910e-01]]
model -- 1 new_A: 
[[ 1.00045180e+00  9.37414536e-01  6.07592153e-04 -4.32690165e-02]
 [ 2.07203154e-04  9.64914271e-01  4.77359643e-04 -3.98209323e-02]
 [-2.50182147e-04 -2.62230027e-02  1.00027735e+00  9.38608261e-01]
 [-2.74694665e-04 -2.80728319e-03 -3.51923425e-05  9.81487297e-01]]
model -- 0 new_Q: 
[[ 1.74790632  2.20811123 -0.02116127 -0.03800127]
 [ 2.20811041  4.37563281  0.16351416  0.18117641]
 [-0.02105972  0.16357232  1.50678647  1.86907839]
 [-0.03793978  0.18128875  1.86907893  3.70799429]]
model -- 1 new_Q: 
[[ 1.74790754  2.20810957 -0.02116348 -0.03800285]
 [ 2.20810875  4.37563032  0.16351335  0.18117467]
 [-0.02106192  0.16357151  1.50678908  1.86908115]
 [-0.037

-1702.7463417848694
model -- 0 new_A: 
[[ 1.00045305e+00  9.37260738e-01  6.08886267e-04 -4.33495203e-02]
 [ 2.07954965e-04  9.64809285e-01  4.78290639e-04 -3.98907026e-02]
 [-2.50447662e-04 -2.62990739e-02  1.00027830e+00  9.38450511e-01]
 [-2.74569800e-04 -2.88587780e-03 -3.43278341e-05  9.81374726e-01]]
model -- 1 new_A: 
[[ 1.00045305e+00  9.37260805e-01  6.08885018e-04 -4.33498464e-02]
 [ 2.07948450e-04  9.64809370e-01  4.78289272e-04 -3.98910203e-02]
 [-2.50444675e-04 -2.62990695e-02  1.00027830e+00  9.38450751e-01]
 [-2.74566979e-04 -2.88589909e-03 -3.43278507e-05  9.81374956e-01]]
model -- 0 new_Q: 
[[ 1.7512082   2.2140615  -0.02119342 -0.03577612]
 [ 2.21406071  4.38913953  0.16476486  0.18497947]
 [-0.02109302  0.1648221   1.50993129  1.87439237]
 [-0.03571557  0.18508878  1.87439292  3.71924721]]
model -- 1 new_Q: 
[[ 1.75120892  2.21406049 -0.02119472 -0.03577704]
 [ 2.21405969  4.38913802  0.16476439  0.18497845]
 [-0.02109432  0.16482163  1.50993284  1.87439402]
 [-0.035

-1702.7479570308178
model -- 0 new_A: 
[[ 1.00045420e+00  9.37121649e-01  6.10043743e-04 -4.34197199e-02]
 [ 2.08080794e-04  9.64786434e-01  4.78507851e-04 -3.99107510e-02]
 [-2.50740993e-04 -2.63649415e-02  1.00027913e+00  9.38307329e-01]
 [-2.74491783e-04 -2.91108533e-03 -3.40711393e-05  9.81344603e-01]]
model -- 1 new_A: 
[[ 1.00045419e+00  9.37121689e-01  6.10042985e-04 -4.34199176e-02]
 [ 2.08076865e-04  9.64786486e-01  4.78507025e-04 -3.99109425e-02]
 [-2.50739178e-04 -2.63649389e-02  1.00027913e+00  9.38307475e-01]
 [-2.74490077e-04 -2.91109837e-03 -3.40711486e-05  9.81344743e-01]]
model -- 0 new_Q: 
[[ 1.75472257  2.21535684 -0.02143284 -0.0346193 ]
 [ 2.21535608  4.39284322  0.16545195  0.18710834]
 [-0.02133254  0.16550897  1.51313601  1.87578452]
 [-0.03455897  0.18721628  1.87578506  3.72240356]]
model -- 1 new_Q: 
[[ 1.75472301  2.21535625 -0.02143363 -0.03461988]
 [ 2.21535548  4.39284234  0.16545165  0.18710771]
 [-0.02133333  0.16550868  1.51313697  1.87578553]
 [-0.034

-1702.7487942618232
model -- 0 new_A: 
[[ 1.00045531e+00  9.36987200e-01  6.11157435e-04 -4.34860958e-02]
 [ 2.07990044e-04  9.64792086e-01  4.78478799e-04 -3.99137116e-02]
 [-2.51048470e-04 -2.64273774e-02  1.00027991e+00  9.38168534e-01]
 [-2.74453334e-04 -2.91521603e-03 -3.40460922e-05  9.81344121e-01]]
model -- 1 new_A: 
[[ 1.00045531e+00  9.36987225e-01  6.11156971e-04 -4.34862166e-02]
 [ 2.07987642e-04  9.64792117e-01  4.78478295e-04 -3.99138287e-02]
 [-2.51047361e-04 -2.64273758e-02  1.00027991e+00  9.38168623e-01]
 [-2.74452295e-04 -2.91522382e-03 -3.40460940e-05  9.81344205e-01]]
model -- 0 new_Q: 
[[ 1.7583016   2.2150135  -0.02174331 -0.0339986 ]
 [ 2.21501277  4.39311033  0.16598358  0.18852304]
 [-0.0216426   0.16604071  1.51634757  1.87582525]
 [-0.03393814  0.18863035  1.87582577  3.72278109]]
model -- 1 new_Q: 
[[ 1.75830186  2.21501311 -0.02174379 -0.03399893]
 [ 2.21501239  4.39310977  0.16598342  0.18852268]
 [-0.02164308  0.16604055  1.51634813  1.87582584]
 [-0.033

-1702.7491870367521
model -- 0 new_A: 
[[ 1.00045642e+00  9.36853826e-01  6.12260155e-04 -4.35512992e-02]
 [ 2.07822953e-04  9.64807554e-01  4.78365588e-04 -3.99110251e-02]
 [-2.51362784e-04 -2.64888215e-02  1.00028068e+00  9.38030697e-01]
 [-2.74436814e-04 -2.91109437e-03 -3.41090799e-05  9.81354334e-01]]
model -- 1 new_A: 
[[ 1.00045642e+00  9.36853841e-01  6.12259870e-04 -4.35513749e-02]
 [ 2.07821474e-04  9.64807573e-01  4.78365281e-04 -3.99110978e-02]
 [-2.51362084e-04 -2.64888206e-02  1.00028068e+00  9.38030753e-01]
 [-2.74436161e-04 -2.91109951e-03 -3.41090842e-05  9.81354388e-01]]
model -- 0 new_Q: 
[[ 1.7618973   2.21409057 -0.02207822 -0.03362506]
 [ 2.21408988  4.39217859  0.1664852   0.18964958]
 [-0.02197699  0.16654255  1.51955504  1.87540065]
 [-0.03356435  0.18975651  1.87540116  3.72220992]]
model -- 1 new_Q: 
[[ 1.76189749  2.21409035 -0.02207853 -0.03362528]
 [ 2.21408966  4.39217826  0.16648508  0.18964933]
 [-0.02197732  0.16654243  1.51955542  1.87540105]
 [-0.033

-1702.749433825873
model -- 0 new_A: 
[[ 1.00045754e+00  9.36720270e-01  6.13363532e-04 -4.36163065e-02]
 [ 2.07628890e-04  9.64826369e-01  4.78224047e-04 -3.99065421e-02]
 [-2.51681143e-04 -2.65501275e-02  1.00028146e+00  9.37892649e-01]
 [-2.74431037e-04 -2.90376627e-03 -3.42053956e-05  9.81368396e-01]]
model -- 1 new_A: 
[[ 1.00045754e+00  9.36720279e-01  6.13363351e-04 -4.36163542e-02]
 [ 2.07627960e-04  9.64826381e-01  4.78223852e-04 -3.99065876e-02]
 [-2.51680702e-04 -2.65501269e-02  1.00028146e+00  9.37892684e-01]
 [-2.74430628e-04 -2.90376953e-03 -3.42053984e-05  9.81368429e-01]]
model -- 0 new_Q: 
[[ 1.76549223  2.21295961 -0.02242255 -0.03335947]
 [ 2.21295896  4.39083299  0.16698937  0.19066569]
 [-0.02232087  0.16704691  1.52275485  1.87481523]
 [-0.03329856  0.19077223  1.87481572  3.72131906]]
model -- 1 new_Q: 
[[ 1.76549235  2.21295947 -0.02242277 -0.03335962]
 [ 2.21295883  4.39083279  0.16698929  0.19066553]
 [-0.0223211   0.16704683  1.52275515  1.87481548]
 [-0.0332

-1702.7496591576796
model -- 0 new_A: 
[[ 1.00045866e+00  9.36586094e-01  6.14471650e-04 -4.36814725e-02]
 [ 2.07425328e-04  9.64846300e-01  4.78073250e-04 -3.99015276e-02]
 [-2.52002514e-04 -2.66115889e-02  1.00028223e+00  9.37753996e-01]
 [-2.74430221e-04 -2.89521402e-03 -3.43141302e-05  9.81383811e-01]]
model -- 1 new_A: 
[[ 1.00045866e+00  9.36586101e-01  6.14471532e-04 -4.36815038e-02]
 [ 2.07424724e-04  9.64846308e-01  4.78073124e-04 -3.99015572e-02]
 [-2.52002223e-04 -2.66115885e-02  1.00028223e+00  9.37754019e-01]
 [-2.74429952e-04 -2.89521613e-03 -3.43141332e-05  9.81383833e-01]]
model -- 0 new_Q: 
[[ 1.76907961  2.21175157 -0.02277162 -0.03313878]
 [ 2.21175097  4.38934978  0.16750158  0.19164276]
 [-0.02266951  0.16755929  1.52594535  1.87417384]
 [-0.03307767  0.19174887  1.87417431  3.72032566]]
model -- 1 new_Q: 
[[ 1.7690797   2.21175148 -0.02277177 -0.03313887]
 [ 2.21175088  4.38934966  0.16750153  0.19164265]
 [-0.02266966  0.16755924  1.52594553  1.874174  ]
 [-0.033

-1702.7499085781874
model -- 0 new_A: 
[[ 1.00045978e+00  9.36451146e-01  6.15585945e-04 -4.37469273e-02]
 [ 2.07218494e-04  9.64866580e-01  4.77919672e-04 -3.98963865e-02]
 [-2.52326515e-04 -2.66733026e-02  1.00028301e+00  9.37614611e-01]
 [-2.74431613e-04 -2.88621789e-03 -3.44272518e-05  9.81399666e-01]]
model -- 1 new_A: 
[[ 1.00045978e+00  9.36451150e-01  6.15585867e-04 -4.37469473e-02]
 [ 2.07218095e-04  9.64866585e-01  4.77919588e-04 -3.98964059e-02]
 [-2.52326331e-04 -2.66733022e-02  1.00028301e+00  9.37614626e-01]
 [-2.74431443e-04 -2.88621898e-03 -3.44272517e-05  9.81399680e-01]]
model -- 0 new_Q: 
[[ 1.77265659  2.21051292 -0.02312395 -0.03293535]
 [ 2.21051236  4.38782669  0.16802096  0.19260879]
 [-0.02302131  0.16807887  1.52912522  1.87351275]
 [-0.03287402  0.19271453  1.87351319  3.71930521]]
model -- 1 new_Q: 
[[ 1.77265661  2.21051285 -0.02312399 -0.03293539]
 [ 2.21051229  4.38782659  0.16802095  0.19260874]
 [-0.02302135  0.16807886  1.52912524  1.87351283]
 [-0.032

-1702.7501980286147
model -- 0 new_A: 
[[ 1.00046092e+00  9.36315373e-01  6.16706902e-04 -4.38127155e-02]
 [ 2.07010645e-04  9.64886944e-01  4.77765499e-04 -3.98912424e-02]
 [-2.52653006e-04 -2.67353010e-02  1.00028379e+00  9.37474454e-01]
 [-2.74433982e-04 -2.87708671e-03 -3.45416396e-05  9.81415619e-01]]
model -- 1 new_A: 
[[ 1.00046092e+00  9.36315376e-01  6.16706854e-04 -4.38127279e-02]
 [ 2.07010400e-04  9.64886947e-01  4.77765448e-04 -3.98912544e-02]
 [-2.52652891e-04 -2.67353009e-02  1.00028379e+00  9.37474463e-01]
 [-2.74433876e-04 -2.87708751e-03 -3.45416378e-05  9.81415627e-01]]
model -- 0 new_Q: 
[[ 1.77622173  2.20926042 -0.02347902 -0.03273744]
 [ 2.2092599   4.38629879  0.16854591  0.19357444]
 [-0.02337569  0.16860415  1.5322938   1.87284471]
 [-0.03267576  0.19367997  1.87284513  3.71828443]]
model -- 1 new_Q: 
[[ 1.77622175  2.20926037 -0.02347906 -0.03273748]
 [ 2.20925986  4.38629873  0.1685459   0.1935744 ]
 [-0.02337574  0.16860414  1.53229385  1.87284476]
 [-0.032

-1702.7505324875647
model -- 0 new_A: 
[[ 1.00046206e+00  9.36178757e-01  6.17834690e-04 -4.38788527e-02]
 [ 2.06802622e-04  9.64907299e-01  4.77611494e-04 -3.98861343e-02]
 [-2.52981940e-04 -2.67975929e-02  1.00028458e+00  9.37333514e-01]
 [-2.74436804e-04 -2.86793939e-03 -3.46561162e-05  9.81431546e-01]]
model -- 1 new_A: 
[[ 1.00046206e+00  9.36178759e-01  6.17834661e-04 -4.38788613e-02]
 [ 2.06802465e-04  9.64907301e-01  4.77611465e-04 -3.98861425e-02]
 [-2.52981858e-04 -2.67975930e-02  1.00028458e+00  9.37333520e-01]
 [-2.74436729e-04 -2.86794020e-03 -3.46561119e-05  9.81431551e-01]]
model -- 0 new_Q: 
[[ 1.77977424  2.20800022 -0.02383645 -0.03253999]
 [ 2.20799975  4.38477889  0.16907557  0.19454399]
 [-0.02373269  0.16913398  1.53545047  1.87217404]
 [-0.03247811  0.19464911  1.87217444  3.71727254]]
model -- 1 new_Q: 
[[ 1.77977426  2.20800019 -0.02383647 -0.03254002]
 [ 2.20799973  4.38477885  0.16907555  0.19454396]
 [-0.0237327   0.16913396  1.53545048  1.87217408]
 [-0.032

-1702.7509137645006
model -- 0 new_A: 
[[ 1.00046321e+00  9.36041294e-01  6.18969352e-04 -4.39453439e-02]
 [ 2.06594733e-04  9.64927611e-01  4.77457910e-04 -3.98810725e-02]
 [-2.53313288e-04 -2.68601800e-02  1.00028537e+00  9.37191791e-01]
 [-2.74439839e-04 -2.85882618e-03 -3.47701878e-05  9.81447395e-01]]
model -- 1 new_A: 
[[ 1.00046321e+00  9.36041294e-01  6.18969335e-04 -4.39453487e-02]
 [ 2.06594643e-04  9.64927612e-01  4.77457892e-04 -3.98810769e-02]
 [-2.53313245e-04 -2.68601800e-02  1.00028537e+00  9.37191794e-01]
 [-2.74439800e-04 -2.85882662e-03 -3.47701840e-05  9.81447398e-01]]
model -- 0 new_Q: 
[[ 1.78331345  2.20673467 -0.02419621 -0.03234097]
 [ 2.20673425  4.38327175  0.16960922  0.19551885]
 [-0.02409196  0.16966783  1.53859476  1.87150244]
 [-0.03227887  0.19562357  1.87150282  3.71627319]]
model -- 1 new_Q: 
[[ 1.78331347  2.20673465 -0.02419623 -0.03234098]
 [ 2.20673423  4.38327173  0.16960921  0.19551883]
 [-0.02409198  0.16966782  1.53859481  1.87150247]
 [-0.032

-1702.7513420958858
model -- 0 new_A: 
[[ 1.00046437e+00  9.35902982e-01  6.20110895e-04 -4.40121899e-02]
 [ 2.06387116e-04  9.64947869e-01  4.77304841e-04 -3.98760590e-02]
 [-2.53647055e-04 -2.69230601e-02  1.00028616e+00  9.37049286e-01]
 [-2.74443007e-04 -2.84976522e-03 -3.48836763e-05  9.81463150e-01]]
model -- 1 new_A: 
[[ 1.00046437e+00  9.35902982e-01  6.20110886e-04 -4.40121917e-02]
 [ 2.06387070e-04  9.64947869e-01  4.77304831e-04 -3.98760610e-02]
 [-2.53647041e-04 -2.69230600e-02  1.00028616e+00  9.37049287e-01]
 [-2.74442994e-04 -2.84976519e-03 -3.48836752e-05  9.81463151e-01]]
model -- 0 new_Q: 
[[ 1.78683869  2.20546474 -0.02455805 -0.0321395 ]
 [ 2.20546437  4.38177937  0.1701465   0.19649945]
 [-0.02445326  0.17020531  1.54172614  1.87083048]
 [-0.03207717  0.19660377  1.87083083  3.71528772]]
model -- 1 new_Q: 
[[ 1.78683868  2.20546473 -0.02455805 -0.0321395 ]
 [ 2.20546436  4.38177936  0.1701465   0.19649945]
 [-0.02445327  0.17020532  1.54172616  1.87083048]
 [-0.032

-1702.751817345421
model -- 0 new_A: 
[[ 1.00046553e+00  9.35763823e-01  6.21259306e-04 -4.40793894e-02]
 [ 2.06179844e-04  9.64968065e-01  4.77152329e-04 -3.98710936e-02]
 [-2.53983236e-04 -2.69862312e-02  1.00028696e+00  9.36906004e-01]
 [-2.74446264e-04 -2.84076594e-03 -3.49964896e-05  9.81478799e-01]]
model -- 1 new_A: 
[[ 1.00046553e+00  9.35763823e-01  6.21259304e-04 -4.40793892e-02]
 [ 2.06179829e-04  9.64968065e-01  4.77152325e-04 -3.98710940e-02]
 [-2.53983241e-04 -2.69862311e-02  1.00028696e+00  9.36906004e-01]
 [-2.74446267e-04 -2.84076573e-03 -3.49964869e-05  9.81478799e-01]]
model -- 0 new_Q: 
[[ 1.79034946  2.20419099 -0.02492192 -0.03193527]
 [ 2.20419067  4.38030283  0.17068724  0.19748587]
 [-0.02481658  0.17074629  1.54484436  1.87015843]
 [-0.03187268  0.19758987  1.87015876  3.7143168 ]]
model -- 1 new_Q: 
[[ 1.79034943  2.20419098 -0.02492188 -0.03193526]
 [ 2.20419065  4.38030281  0.17068725  0.19748589]
 [-0.02481655  0.1707463   1.54484434  1.87015842]
 [-0.0318

-1702.752339136686
model -- 0 new_A: 
[[ 1.00046671e+00  9.35623820e-01  6.22414565e-04 -4.41469407e-02]
 [ 2.05972951e-04  9.64988196e-01  4.77000402e-04 -3.98661775e-02]
 [-2.54321829e-04 -2.70496910e-02  1.00028777e+00  9.36761949e-01]
 [-2.74449606e-04 -2.83183032e-03 -3.51086037e-05  9.81494341e-01]]
model -- 1 new_A: 
[[ 1.00046671e+00  9.35623820e-01  6.22414568e-04 -4.41469388e-02]
 [ 2.05972966e-04  9.64988196e-01  4.77000404e-04 -3.98661763e-02]
 [-2.54321850e-04 -2.70496909e-02  1.00028777e+00  9.36761947e-01]
 [-2.74449624e-04 -2.83182994e-03 -3.51086018e-05  9.81494339e-01]]
model -- 0 new_Q: 
[[ 1.79384514  2.20291369 -0.02528748 -0.03172809]
 [ 2.20291341  4.37884263  0.17123136  0.19847814]
 [-0.02518166  0.17129061  1.54794884  1.86948643]
 [-0.03166528  0.19858173  1.86948673  3.71336075]]
model -- 1 new_Q: 
[[ 1.79384513  2.20291368 -0.02528747 -0.03172807]
 [ 2.2029134   4.37884262  0.17123138  0.19847817]
 [-0.02518167  0.17129063  1.54794885  1.86948641]
 [-0.0316

-1702.7529069795442
model -- 0 new_A: 
[[ 1.00046789e+00  9.35482974e-01  6.23576651e-04 -4.42148414e-02]
 [ 2.05766476e-04  9.65008260e-01  4.76849078e-04 -3.98613100e-02]
 [-2.54662839e-04 -2.71134369e-02  1.00028857e+00  9.36617123e-01]
 [-2.74453035e-04 -2.82296017e-03 -3.52199990e-05  9.81509771e-01]]
model -- 1 new_A: 
[[ 1.00046789e+00  9.35482973e-01  6.23576658e-04 -4.42148402e-02]
 [ 2.05766503e-04  9.65008260e-01  4.76849085e-04 -3.98613089e-02]
 [-2.54662851e-04 -2.71134370e-02  1.00028857e+00  9.36617122e-01]
 [-2.74453045e-04 -2.82296025e-03 -3.52199964e-05  9.81509770e-01]]
model -- 0 new_Q: 
[[ 1.79732522  2.2016331  -0.02565473 -0.03151793]
 [ 2.20163287  4.37739927  0.17177877  0.19947613]
 [-0.02554839  0.17183823  1.55103932  1.86881453]
 [-0.03145488  0.19957932  1.86881481  3.71241979]]
model -- 1 new_Q: 
[[ 1.79732523  2.2016331  -0.02565473 -0.03151793]
 [ 2.20163287  4.37739928  0.17177877  0.19947613]
 [-0.02554839  0.17183822  1.55103931  1.86881453]
 [-0.031

-1702.7535205911431
model -- 0 new_A: 
[[ 1.00046907e+00  9.35341288e-01  6.24745545e-04 -4.42830897e-02]
 [ 2.05560451e-04  9.65028254e-01  4.76698379e-04 -3.98564916e-02]
 [-2.55006266e-04 -2.71774665e-02  1.00028938e+00  9.36471531e-01]
 [-2.74456551e-04 -2.81415729e-03 -3.53306515e-05  9.81525087e-01]]
model -- 1 new_A: 
[[ 1.00046907e+00  9.35341288e-01  6.24745544e-04 -4.42830916e-02]
 [ 2.05560457e-04  9.65028254e-01  4.76698380e-04 -3.98564917e-02]
 [-2.55006242e-04 -2.71774665e-02  1.00028938e+00  9.36471534e-01]
 [-2.74456532e-04 -2.81415774e-03 -3.53306605e-05  9.81525090e-01]]
model -- 0 new_Q: 
[[ 1.8007892   2.20034944 -0.02602343 -0.03130476]
 [ 2.20034926  4.37597314  0.17232943  0.20047972]
 [-0.02591654  0.17238912  1.55411537  1.86814288]
 [-0.03124145  0.20058258  1.86814313  3.71149424]]
model -- 1 new_Q: 
[[ 1.80078925  2.20034948 -0.02602346 -0.03130479]
 [ 2.2003493   4.3759732   0.1723294   0.20047967]
 [-0.02591657  0.17238908  1.55411536  1.86814293]
 [-0.031

-1702.7541791624892
model -- 0 new_A: 
[[ 1.00047027e+00  9.35198765e-01  6.25921218e-04 -4.43516844e-02]
 [ 2.05354902e-04  9.65048175e-01  4.76548320e-04 -3.98517226e-02]
 [-2.55352092e-04 -2.72417771e-02  1.00029020e+00  9.36325179e-01]
 [-2.74460148e-04 -2.80542103e-03 -3.54405776e-05  9.81540292e-01]]
model -- 1 new_A: 
[[ 1.00047027e+00  9.35198765e-01  6.25921211e-04 -4.43516868e-02]
 [ 2.05354862e-04  9.65048175e-01  4.76548314e-04 -3.98517249e-02]
 [-2.55352067e-04 -2.72417772e-02  1.00029020e+00  9.36325181e-01]
 [-2.74460126e-04 -2.80542131e-03 -3.54405770e-05  9.81540294e-01]]
model -- 0 new_Q: 
[[ 1.80423665  2.19906295 -0.02639341 -0.03108853]
 [ 2.19906282  4.37456464  0.17288334  0.20148886]
 [-0.02628612  0.17294317  1.55717678  1.86747145]
 [-0.03102506  0.20159126  1.86747167  3.71058408]]
model -- 1 new_Q: 
[[ 1.80423665  2.19906294 -0.02639342 -0.03108854]
 [ 2.19906281  4.37456463  0.17288333  0.20148885]
 [-0.02628613  0.17294317  1.5571768   1.86747145]
 [-0.031

-1702.754882446661
model -- 0 new_A: 
[[ 1.00047147e+00  9.35055407e-01  6.27103646e-04 -4.44206235e-02]
 [ 2.05149830e-04  9.65068021e-01  4.76398914e-04 -3.98470043e-02]
 [-2.55700324e-04 -2.73063659e-02  1.00029102e+00  9.36178070e-01]
 [-2.74463836e-04 -2.79675186e-03 -3.55497587e-05  9.81555381e-01]]
model -- 1 new_A: 
[[ 1.00047147e+00  9.35055407e-01  6.27103641e-04 -4.44206250e-02]
 [ 2.05149805e-04  9.65068021e-01  4.76398909e-04 -3.98470056e-02]
 [-2.55700309e-04 -2.73063659e-02  1.00029102e+00  9.36178071e-01]
 [-2.74463823e-04 -2.79675199e-03 -3.55497587e-05  9.81555383e-01]]
model -- 0 new_Q: 
[[ 1.80766699  2.19777379 -0.02676455 -0.03086929]
 [ 2.19777371  4.37317405  0.17344035  0.20250338]
 [-0.02665673  0.17350039  1.56022302  1.86680029]
 [-0.03080558  0.20260537  1.86680049  3.70968954]]
model -- 1 new_Q: 
[[ 1.80766699  2.19777378 -0.02676456 -0.0308693 ]
 [ 2.19777371  4.37317404  0.17344035  0.20250337]
 [-0.02665675  0.17350039  1.56022303  1.8668003 ]
 [-0.0308

-1702.7556298705517
model -- 0 new_A: 
[[ 1.00047268e+00  9.34911218e-01  6.28292803e-04 -4.44899043e-02]
 [ 2.04945278e-04  9.65087790e-01  4.76250174e-04 -3.98423352e-02]
 [-2.56050963e-04 -2.73712302e-02  1.00029184e+00  9.36030209e-01]
 [-2.74467623e-04 -2.78815065e-03 -3.56581854e-05  9.81570354e-01]]
model -- 1 new_A: 
[[ 1.00047268e+00  9.34911218e-01  6.28292801e-04 -4.44899050e-02]
 [ 2.04945264e-04  9.65087791e-01  4.76250172e-04 -3.98423359e-02]
 [-2.56050959e-04 -2.73712303e-02  1.00029184e+00  9.36030209e-01]
 [-2.74467618e-04 -2.78815075e-03 -3.56581844e-05  9.81570354e-01]]
model -- 0 new_Q: 
[[ 1.81107983  2.19648218 -0.02713672 -0.03064703]
 [ 2.19648215  4.37180172  0.17400044  0.20352312]
 [-0.02702831  0.17406071  1.56325395  1.86612953]
 [-0.03058306  0.20362473  1.86612971  3.70881086]]
model -- 1 new_Q: 
[[ 1.81107982  2.19648217 -0.02713668 -0.03064703]
 [ 2.19648215  4.37180171  0.17400044  0.20352312]
 [-0.0270283   0.17406071  1.56325392  1.86612954]
 [-0.030

-1702.756420835171
model -- 0 new_A: 
[[ 1.00047390e+00  9.34766200e-01  6.29488662e-04 -4.45595250e-02]
 [ 2.04741264e-04  9.65107482e-01  4.76102112e-04 -3.98377155e-02]
 [-2.56404004e-04 -2.74363675e-02  1.00029266e+00  9.35881600e-01]
 [-2.74471506e-04 -2.77961785e-03 -3.57658526e-05  9.81585209e-01]]
model -- 1 new_A: 
[[ 1.00047390e+00  9.34766200e-01  6.29488663e-04 -4.45595236e-02]
 [ 2.04741272e-04  9.65107482e-01  4.76102111e-04 -3.98377146e-02]
 [-2.56404021e-04 -2.74363673e-02  1.00029266e+00  9.35881599e-01]
 [-2.74471520e-04 -2.77961754e-03 -3.57658520e-05  9.81585208e-01]]
model -- 0 new_Q: 
[[ 1.81447472  2.19518829 -0.02750966 -0.03042176]
 [ 2.19518832  4.37044793  0.17456361  0.20454798]
 [-0.02740071  0.17462412  1.56626917  1.8654592 ]
 [-0.03035753  0.20464925  1.86545935  3.70794814]]
model -- 1 new_Q: 
[[ 1.81447471  2.19518828 -0.02750964 -0.03042175]
 [ 2.19518831  4.37044792  0.17456363  0.20454799]
 [-0.02740069  0.17462413  1.56626917  1.86545919]
 [-0.0303

-1702.7572546801334
model -- 0 new_A: 
[[ 1.00047512e+00  9.34620357e-01  6.30691196e-04 -4.46294830e-02]
 [ 2.04537810e-04  9.65127092e-01  4.75954745e-04 -3.98331458e-02]
 [-2.56759451e-04 -2.75017750e-02  1.00029349e+00  9.35732247e-01]
 [-2.74475501e-04 -2.77115260e-03 -3.58727651e-05  9.81599946e-01]]
model -- 1 new_A: 
[[ 1.00047512e+00  9.34620357e-01  6.30691201e-04 -4.46294807e-02]
 [ 2.04537838e-04  9.65127092e-01  4.75954749e-04 -3.98331441e-02]
 [-2.56759475e-04 -2.75017749e-02  1.00029349e+00  9.35732245e-01]
 [-2.74475523e-04 -2.77115229e-03 -3.58727640e-05  9.81599944e-01]]
model -- 0 new_Q: 
[[ 1.81785124  2.19389231 -0.02788325 -0.03019343]
 [ 2.19389239  4.36911298  0.17512982  0.20557791]
 [-0.02777377  0.17519054  1.56926853  1.8647893 ]
 [-0.03012895  0.2056788   1.86478942  3.70710145]]
model -- 1 new_Q: 
[[ 1.81785121  2.1938923  -0.02788322 -0.03019341]
 [ 2.19389238  4.36911297  0.17512984  0.20557793]
 [-0.02777374  0.17519055  1.5692685   1.86478927]
 [-0.030

-1702.7581310350379
model -- 0 new_A: 
[[ 1.00047636e+00  9.34473693e-01  6.31900375e-04 -4.46997755e-02]
 [ 2.04334945e-04  9.65146620e-01  4.75808086e-04 -3.98286256e-02]
 [-2.57117297e-04 -2.75674505e-02  1.00029433e+00  9.35582155e-01]
 [-2.74479613e-04 -2.76275479e-03 -3.59789209e-05  9.81614564e-01]]
model -- 1 new_A: 
[[ 1.00047636e+00  9.34473692e-01  6.31900383e-04 -4.46997734e-02]
 [ 2.04334986e-04  9.65146619e-01  4.75808094e-04 -3.98286234e-02]
 [-2.57117316e-04 -2.75674505e-02  1.00029433e+00  9.35582154e-01]
 [-2.74479631e-04 -2.76275468e-03 -3.59789216e-05  9.81614563e-01]]
model -- 0 new_Q: 
[[ 1.82120902  2.19259446 -0.02825729 -0.0299621 ]
 [ 2.19259459  4.36779718  0.17569903  0.20661274]
 [-0.02814733  0.17575993  1.57225166  1.86411986]
 [-0.02989741  0.2067132   1.86411995  3.70627085]]
model -- 1 new_Q: 
[[ 1.82120903  2.19259448 -0.02825728 -0.0299621 ]
 [ 2.19259461  4.3677972   0.17569903  0.20661274]
 [-0.02814731  0.17575993  1.57225165  1.86411986]
 [-0.029

-1702.759049129049
model -- 0 new_A: 
[[ 1.00047760e+00  9.34326209e-01  6.33116170e-04 -4.47704007e-02]
 [ 2.04132686e-04  9.65166064e-01  4.75662144e-04 -3.98241549e-02]
 [-2.57477534e-04 -2.76333913e-02  1.00029516e+00  9.35431328e-01]
 [-2.74483847e-04 -2.75442425e-03 -3.60843215e-05  9.81629063e-01]]
model -- 1 new_A: 
[[ 1.00047760e+00  9.34326209e-01  6.33116178e-04 -4.47703979e-02]
 [ 2.04132731e-04  9.65166063e-01  4.75662153e-04 -3.98241523e-02]
 [-2.57477562e-04 -2.76333913e-02  1.00029516e+00  9.35431326e-01]
 [-2.74483872e-04 -2.75442404e-03 -3.60843187e-05  9.81629061e-01]]
model -- 0 new_Q: 
[[ 1.82454767  2.1912949  -0.02863161 -0.02972779]
 [ 2.19129508  4.36650077  0.17627116  0.20765234]
 [-0.02852121  0.17633222  1.57521825  1.86345096]
 [-0.02966292  0.20775231  1.86345103  3.70545654]]
model -- 1 new_Q: 
[[ 1.82454767  2.19129491 -0.0286316  -0.02972778]
 [ 2.19129509  4.36650078  0.17627116  0.20765235]
 [-0.02852119  0.17633222  1.5752182   1.86345094]
 [-0.0296

-1702.7600084745745
model -- 0 new_A: 
[[ 1.00047884e+00  9.34177910e-01  6.34338554e-04 -4.48413567e-02]
 [ 2.03931050e-04  9.65185422e-01  4.75516927e-04 -3.98197329e-02]
 [-2.57840174e-04 -2.76995936e-02  1.00029600e+00  9.35279772e-01]
 [-2.74488203e-04 -2.74616199e-03 -3.61889528e-05  9.81643441e-01]]
model -- 1 new_A: 
[[ 1.00047884e+00  9.34177910e-01  6.34338562e-04 -4.48413549e-02]
 [ 2.03931089e-04  9.65185422e-01  4.75516935e-04 -3.98197310e-02]
 [-2.57840190e-04 -2.76995936e-02  1.00029600e+00  9.35279771e-01]
 [-2.74488218e-04 -2.74616190e-03 -3.61889542e-05  9.81643440e-01]]
model -- 0 new_Q: 
[[ 1.82786684  2.18999377 -0.02900622 -0.02949049]
 [ 2.189994    4.36522394  0.1768461   0.20869656]
 [-0.0288952   0.17690741  1.57816819  1.86278261]
 [-0.02942534  0.20879618  1.86278265  3.70465854]]
model -- 1 new_Q: 
[[ 1.82786685  2.18999378 -0.02900622 -0.02949049]
 [ 2.18999402  4.36522397  0.17684609  0.20869655]
 [-0.02889521  0.1769074   1.57816822  1.86278261]
 [-0.029

-1702.7610083693992
model -- 0 new_A: 
[[ 1.00048010e+00  9.34028800e-01  6.35567492e-04 -4.49126410e-02]
 [ 2.03730055e-04  9.65204694e-01  4.75372443e-04 -3.98153599e-02]
 [-2.58205197e-04 -2.77660559e-02  1.00029685e+00  9.35127491e-01]
 [-2.74492686e-04 -2.73796739e-03 -3.62928212e-05  9.81657699e-01]]
model -- 1 new_A: 
[[ 1.00048010e+00  9.34028800e-01  6.35567498e-04 -4.49126388e-02]
 [ 2.03730086e-04  9.65204694e-01  4.75372449e-04 -3.98153583e-02]
 [-2.58205220e-04 -2.77660559e-02  1.00029685e+00  9.35127489e-01]
 [-2.74492705e-04 -2.73796722e-03 -3.62928203e-05  9.81657697e-01]]
model -- 0 new_Q: 
[[ 1.83116619  2.18869125 -0.02938079 -0.02925023]
 [ 2.18869154  4.36396696  0.17742391  0.2097453 ]
 [-0.02926928  0.17748542  1.58110125  1.86211488]
 [-0.02918486  0.20984452  1.86211489  3.70387703]]
model -- 1 new_Q: 
[[ 1.83116618  2.18869124 -0.02938079 -0.02925022]
 [ 2.18869154  4.36396695  0.17742392  0.20974531]
 [-0.02926928  0.17748542  1.58110127  1.86211487]
 [-0.029

-1702.7620483862434
model -- 0 new_A: 
[[ 1.00048136e+00  9.33878882e-01  6.36802953e-04 -4.49842504e-02]
 [ 2.03529724e-04  9.65223878e-01  4.75228708e-04 -3.98110360e-02]
 [-2.58572611e-04 -2.78327756e-02  1.00029770e+00  9.34974488e-01]
 [-2.74497313e-04 -2.72983982e-03 -3.63959260e-05  9.81671834e-01]]
model -- 1 new_A: 
[[ 1.00048136e+00  9.33878882e-01  6.36802953e-04 -4.49842503e-02]
 [ 2.03529730e-04  9.65223878e-01  4.75228708e-04 -3.98110357e-02]
 [-2.58572610e-04 -2.78327756e-02  1.00029770e+00  9.34974489e-01]
 [-2.74497312e-04 -2.72983978e-03 -3.63959294e-05  9.81671834e-01]]
model -- 0 new_Q: 
[[ 1.83444544  2.18738751 -0.02975529 -0.02900703]
 [ 2.18738786  4.36273005  0.17800451  0.21079847]
 [-0.02964326  0.17806621  1.58401732  1.86144781]
 [-0.02894144  0.21089726  1.8614478   3.70311205]]
model -- 1 new_Q: 
[[ 1.83444545  2.18738752 -0.02975529 -0.02900703]
 [ 2.18738786  4.36273005  0.17800451  0.21079847]
 [-0.02964326  0.17806621  1.58401732  1.86144782]
 [-0.028

-1702.7631277069663
model -- 0 new_A: 
[[ 1.00048263e+00  9.33728160e-01  6.38044903e-04 -4.50561833e-02]
 [ 2.03330064e-04  9.65242972e-01  4.75085724e-04 -3.98067609e-02]
 [-2.58942403e-04 -2.78997499e-02  1.00029855e+00  9.34820770e-01]
 [-2.74502074e-04 -2.72177924e-03 -3.64982723e-05  9.81685849e-01]]
model -- 1 new_A: 
[[ 1.00048263e+00  9.33728160e-01  6.38044900e-04 -4.50561846e-02]
 [ 2.03330051e-04  9.65242972e-01  4.75085722e-04 -3.98067618e-02]
 [-2.58942389e-04 -2.78997499e-02  1.00029855e+00  9.34820771e-01]
 [-2.74502062e-04 -2.72177935e-03 -3.64982747e-05  9.81685850e-01]]
model -- 0 new_Q: 
[[ 1.83770426  2.18608269 -0.03012947 -0.02876088]
 [ 2.18608309  4.36151336  0.17858789  0.21185597]
 [-0.03001701  0.17864975  1.58691602  1.86078138]
 [-0.0286951   0.21195431  1.86078133  3.70236356]]
model -- 1 new_Q: 
[[ 1.83770428  2.1860827  -0.03012951 -0.02876089]
 [ 2.1860831   4.36151337  0.17858788  0.21185596]
 [-0.03001704  0.17864974  1.58691605  1.86078139]
 [-0.028

-1702.7642457879538
model -- 0 new_A: 
[[ 1.00048390e+00  9.33576637e-01  6.39293311e-04 -4.51284386e-02]
 [ 2.03131081e-04  9.65261975e-01  4.74943498e-04 -3.98025352e-02]
 [-2.59314562e-04 -2.79669758e-02  1.00029940e+00  9.34666342e-01]
 [-2.74506966e-04 -2.71378596e-03 -3.65998561e-05  9.81699743e-01]]
model -- 1 new_A: 
[[ 1.00048390e+00  9.33576637e-01  6.39293312e-04 -4.51284373e-02]
 [ 2.03131082e-04  9.65261975e-01  4.74943496e-04 -3.98025346e-02]
 [-2.59314579e-04 -2.79669757e-02  1.00029940e+00  9.34666340e-01]
 [-2.74506980e-04 -2.71378568e-03 -3.65998531e-05  9.81699741e-01]]
model -- 0 new_Q: 
[[ 1.8409424   2.18477693 -0.03050336 -0.02851179]
 [ 2.18477739  4.36031706  0.1791739   0.21291767]
 [-0.03039028  0.179236    1.58979732  1.86011561]
 [-0.02844574  0.21301562  1.86011554  3.70163165]]
model -- 1 new_Q: 
[[ 1.84094238  2.18477691 -0.03050335 -0.02851177]
 [ 2.18477738  4.36031704  0.17917391  0.21291769]
 [-0.03039027  0.17923602  1.58979733  1.86011559]
 [-0.028

-1702.765402038212
model -- 0 new_A: 
[[ 1.00048519e+00  9.33424318e-01  6.40548142e-04 -4.52010119e-02]
 [ 2.02932799e-04  9.65280887e-01  4.74802034e-04 -3.97983573e-02]
 [-2.59689099e-04 -2.80344510e-02  1.00030026e+00  9.34511206e-01]
 [-2.74512012e-04 -2.70585897e-03 -3.67006790e-05  9.81713515e-01]]
model -- 1 new_A: 
[[ 1.00048519e+00  9.33424318e-01  6.40548147e-04 -4.52010103e-02]
 [ 2.02932823e-04  9.65280887e-01  4.74802039e-04 -3.97983561e-02]
 [-2.59689116e-04 -2.80344510e-02  1.00030026e+00  9.34511205e-01]
 [-2.74512026e-04 -2.70585886e-03 -3.67006778e-05  9.81713513e-01]]
model -- 0 new_Q: 
[[ 1.84415958  2.18347038 -0.03087666 -0.0282598 ]
 [ 2.1834709   4.35914134  0.17976261  0.21398347]
 [-0.03076311  0.17982489  1.59266111  1.85945054]
 [-0.02819354  0.21408097  1.85945044  3.70091637]]
model -- 1 new_Q: 
[[ 1.84415958  2.18347038 -0.03087665 -0.02825979]
 [ 2.1834709   4.35914134  0.17976261  0.21398347]
 [-0.0307631   0.17982489  1.59266111  1.85945053]
 [-0.0281

-1702.7665958047937
model -- 0 new_A: 
[[ 1.00048648e+00  9.33271207e-01  6.41809362e-04 -4.52739011e-02]
 [ 2.02735241e-04  9.65299707e-01  4.74661344e-04 -3.97942271e-02]
 [-2.60066003e-04 -2.81021731e-02  1.00030112e+00  9.34355369e-01]
 [-2.74517215e-04 -2.69799811e-03 -3.68007431e-05  9.81727164e-01]]
model -- 1 new_A: 
[[ 1.00048648e+00  9.33271207e-01  6.41809367e-04 -4.52738998e-02]
 [ 2.02735267e-04  9.65299707e-01  4.74661349e-04 -3.97942258e-02]
 [-2.60066017e-04 -2.81021731e-02  1.00030112e+00  9.34355368e-01]
 [-2.74517227e-04 -2.69799806e-03 -3.68007441e-05  9.81727163e-01]]
model -- 0 new_Q: 
[[ 1.84735558  2.18216321 -0.03124927 -0.02800497]
 [ 2.18216378  4.35798639  0.18035389  0.21505319]
 [-0.03113519  0.18041637  1.59550702  1.85878624]
 [-0.02793847  0.21515026  1.8587861   3.70021784]]
model -- 1 new_Q: 
[[ 1.84735558  2.18216322 -0.03124927 -0.02800497]
 [ 2.18216379  4.3579864   0.18035388  0.21505319]
 [-0.0311352   0.18041637  1.59550703  1.85878624]
 [-0.027

-1702.7678262133572
model -- 0 new_A: 
[[ 1.00048777e+00  9.33117307e-01  6.43076940e-04 -4.53471049e-02]
 [ 2.02538411e-04  9.65318433e-01  4.74521426e-04 -3.97901442e-02]
 [-2.60445270e-04 -2.81701386e-02  1.00030199e+00  9.34198836e-01]
 [-2.74522565e-04 -2.69020348e-03 -3.69000527e-05  9.81740692e-01]]
model -- 1 new_A: 
[[ 1.00048777e+00  9.33117307e-01  6.43076947e-04 -4.53471032e-02]
 [ 2.02538436e-04  9.65318433e-01  4.74521432e-04 -3.97901430e-02]
 [-2.60445288e-04 -2.81701387e-02  1.00030199e+00  9.34198834e-01]
 [-2.74522579e-04 -2.69020344e-03 -3.69000495e-05  9.81740690e-01]]
model -- 0 new_Q: 
[[ 1.85053013  2.18085551 -0.03162102 -0.02774723]
 [ 2.18085614  4.35685229  0.18094774  0.21612682]
 [-0.03150647  0.1810104   1.59833508  1.85812262]
 [-0.02768053  0.21622345  1.85812246  3.69953589]]
model -- 1 new_Q: 
[[ 1.85053011  2.1808555  -0.03162101 -0.02774722]
 [ 2.18085614  4.35685228  0.18094775  0.21612682]
 [-0.03150646  0.18101041  1.59833506  1.85812261]
 [-0.027

-1702.7690930452845
model -- 0 new_A: 
[[ 1.00048908e+00  9.32962623e-01  6.44350837e-04 -4.54206200e-02]
 [ 2.02342317e-04  9.65337065e-01  4.74382290e-04 -3.97861091e-02]
 [-2.60826893e-04 -2.82383459e-02  1.00030286e+00  9.34041610e-01]
 [-2.74528083e-04 -2.68247391e-03 -3.69986084e-05  9.81754098e-01]]
model -- 1 new_A: 
[[ 1.00048908e+00  9.32962622e-01  6.44350847e-04 -4.54206178e-02]
 [ 2.02342356e-04  9.65337065e-01  4.74382300e-04 -3.97861073e-02]
 [-2.60826914e-04 -2.82383460e-02  1.00030286e+00  9.34041608e-01]
 [-2.74528101e-04 -2.68247389e-03 -3.69986053e-05  9.81754096e-01]]
model -- 0 new_Q: 
[[ 1.85368309  2.17954743 -0.03199192 -0.02748669]
 [ 2.17954812  4.35573918  0.18154409  0.21720418]
 [-0.03187684  0.18160694  1.60114516  1.85745983]
 [-0.02741977  0.21730036  1.85745963  3.69887077]]
model -- 1 new_Q: 
[[ 1.8536831   2.17954743 -0.03199194 -0.02748668]
 [ 2.17954812  4.35573919  0.18154409  0.21720418]
 [-0.03187687  0.18160694  1.6011452   1.85745982]
 [-0.027

-1702.7703954144952
model -- 0 new_A: 
[[ 1.00049039e+00  9.32807159e-01  6.45631020e-04 -4.54944435e-02]
 [ 2.02146985e-04  9.65355603e-01  4.74243935e-04 -3.97821197e-02]
 [-2.61210870e-04 -2.83067922e-02  1.00030373e+00  9.33883696e-01]
 [-2.74533765e-04 -2.67481008e-03 -3.70964070e-05  9.81767380e-01]]
model -- 1 new_A: 
[[ 1.00049039e+00  9.32807158e-01  6.45631024e-04 -4.54944429e-02]
 [ 2.02146999e-04  9.65355603e-01  4.74243940e-04 -3.97821192e-02]
 [-2.61210874e-04 -2.83067923e-02  1.00030373e+00  9.33883696e-01]
 [-2.74533768e-04 -2.67481010e-03 -3.70964061e-05  9.81767380e-01]]
model -- 0 new_Q: 
[[ 1.8568142   2.17823908 -0.0323617  -0.02722334]
 [ 2.17823982  4.35464718  0.1821429   0.21828518]
 [-0.03224614  0.18220594  1.60393715  1.85679782]
 [-0.0271562   0.21838094  1.8567976   3.69822239]]
model -- 1 new_Q: 
[[ 1.8568142   2.17823908 -0.03236169 -0.02722333]
 [ 2.17823983  4.35464718  0.18214291  0.21828519]
 [-0.03224613  0.18220594  1.60393713  1.85679781]
 [-0.027

-1702.771732747183
model -- 0 new_A: 
[[ 1.00049171e+00  9.32650918e-01  6.46917454e-04 -4.55685742e-02]
 [ 2.01952411e-04  9.65374045e-01  4.74106372e-04 -3.97781776e-02]
 [-2.61597194e-04 -2.83754746e-02  1.00030461e+00  9.33725100e-01]
 [-2.74539617e-04 -2.66721052e-03 -3.71934605e-05  9.81780542e-01]]
model -- 1 new_A: 
[[ 1.00049171e+00  9.32650918e-01  6.46917453e-04 -4.55685749e-02]
 [ 2.01952411e-04  9.65374045e-01  4.74106371e-04 -3.97781777e-02]
 [-2.61597185e-04 -2.83754745e-02  1.00030461e+00  9.33725101e-01]
 [-2.74539609e-04 -2.66721065e-03 -3.71934648e-05  9.81780543e-01]]
model -- 0 new_Q: 
[[ 1.8599233   2.17693058 -0.03273029 -0.02695717]
 [ 2.17693139  4.35357638  0.18274413  0.21936977]
 [-0.0326142   0.18280736  1.60671096  1.85613661]
 [-0.02688981  0.21946508  1.85613635  3.69759073]]
model -- 1 new_Q: 
[[ 1.85992333  2.1769306  -0.0327303  -0.02695718]
 [ 2.1769314   4.3535764   0.18274412  0.21936975]
 [-0.03261421  0.18280735  1.60671096  1.85613663]
 [-0.0268

-1702.773104241926
model -- 0 new_A: 
[[ 1.00049303e+00  9.32493907e-01  6.48210097e-04 -4.56430085e-02]
 [ 2.01758611e-04  9.65392390e-01  4.73969595e-04 -3.97742811e-02]
 [-2.61985848e-04 -2.84443916e-02  1.00030548e+00  9.33565826e-01]
 [-2.74545636e-04 -2.65967500e-03 -3.72897760e-05  9.81793583e-01]]
model -- 1 new_A: 
[[ 1.00049303e+00  9.32493907e-01  6.48210093e-04 -4.56430097e-02]
 [ 2.01758588e-04  9.65392391e-01  4.73969591e-04 -3.97742824e-02]
 [-2.61985836e-04 -2.84443916e-02  1.00030548e+00  9.33565827e-01]
 [-2.74545625e-04 -2.65967510e-03 -3.72897748e-05  9.81793583e-01]]
model -- 0 new_Q: 
[[ 1.86301032  2.17562208 -0.03309751 -0.02668826]
 [ 2.17562294  4.3525269   0.18334778  0.22045782]
 [-0.03298102  0.18341115  1.60946643  1.85547618]
 [-0.02662074  0.22055263  1.85547589  3.69697573]]
model -- 1 new_Q: 
[[ 1.86301033  2.17562207 -0.03309753 -0.02668826]
 [ 2.17562293  4.35252689  0.18334778  0.22045782]
 [-0.03298104  0.18341115  1.60946646  1.85547618]
 [-0.0266

-1702.77450951111
model -- 0 new_A: 
[[ 1.00049437e+00  9.32336128e-01  6.49508914e-04 -4.57177448e-02]
 [ 2.01565581e-04  9.65410640e-01  4.73833609e-04 -3.97704308e-02]
 [-2.62376830e-04 -2.85135402e-02  1.00030637e+00  9.33405880e-01]
 [-2.74551831e-04 -2.65220295e-03 -3.73853514e-05  9.81806502e-01]]
model -- 1 new_A: 
[[ 1.00049437e+00  9.32336128e-01  6.49508911e-04 -4.57177450e-02]
 [ 2.01565564e-04  9.65410640e-01  4.73833606e-04 -3.97704315e-02]
 [-2.62376830e-04 -2.85135401e-02  1.00030637e+00  9.33405880e-01]
 [-2.74551830e-04 -2.65220279e-03 -3.73853493e-05  9.81806502e-01]]
model -- 0 new_Q: 
[[ 1.86607507  2.17431364 -0.03346333 -0.02641662]
 [ 2.17431457  4.35149877  0.18395372  0.22154922]
 [-0.03334639  0.18401725  1.61220358  1.85481659]
 [-0.02634891  0.22164352  1.85481627  3.6963775 ]]
model -- 1 new_Q: 
[[ 1.86607506  2.17431363 -0.03346333 -0.0264166 ]
 [ 2.17431456  4.35149875  0.18395373  0.22154924]
 [-0.03334639  0.18401726  1.6122036   1.85481658]
 [-0.02634

-1702.775947936343
model -- 0 new_A: 
[[ 1.00049571e+00  9.32177586e-01  6.50813874e-04 -4.57927803e-02]
 [ 2.01373339e-04  9.65428793e-01  4.73698411e-04 -3.97666249e-02]
 [-2.62770150e-04 -2.85829171e-02  1.00030725e+00  9.33245264e-01]
 [-2.74558213e-04 -2.64479409e-03 -3.74801869e-05  9.81819300e-01]]
model -- 1 new_A: 
[[ 1.00049571e+00  9.32177586e-01  6.50813869e-04 -4.57927821e-02]
 [ 2.01373322e-04  9.65428793e-01  4.73698407e-04 -3.97666259e-02]
 [-2.62770131e-04 -2.85829171e-02  1.00030725e+00  9.33245266e-01]
 [-2.74558197e-04 -2.64479434e-03 -3.74801888e-05  9.81819301e-01]]
model -- 0 new_Q: 
[[ 1.86911739  2.17300537 -0.03382765 -0.02614229]
 [ 2.17300636  4.35049203  0.18456187  0.22264381]
 [-0.03371011  0.18462562  1.61492232  1.85415785]
 [-0.02607432  0.2227377   1.8541575   3.69579603]]
model -- 1 new_Q: 
[[ 1.86911742  2.17300538 -0.03382768 -0.0261423 ]
 [ 2.17300637  4.35049204  0.18456186  0.22264379]
 [-0.03371015  0.18462561  1.61492236  1.85415788]
 [-0.0260

-1702.7774186366555
model -- 0 new_A: 
[[ 1.00049705e+00  9.32018285e-01  6.52124939e-04 -4.58681133e-02]
 [ 2.01181896e-04  9.65446849e-01  4.73564002e-04 -3.97628630e-02]
 [-2.63165790e-04 -2.86525199e-02  1.00030814e+00  9.33083986e-01]
 [-2.74564771e-04 -2.63744809e-03 -3.75742942e-05  9.81831978e-01]]
model -- 1 new_A: 
[[ 1.00049705e+00  9.32018285e-01  6.52124929e-04 -4.58681159e-02]
 [ 2.01181845e-04  9.65446850e-01  4.73563993e-04 -3.97628657e-02]
 [-2.63165764e-04 -2.86525200e-02  1.00030814e+00  9.33083988e-01]
 [-2.74564748e-04 -2.63744818e-03 -3.75742917e-05  9.81831979e-01]]
model -- 0 new_Q: 
[[ 1.87213722  2.17169736 -0.03419032 -0.02586525]
 [ 2.1716984   4.34950674  0.18517229  0.22374158]
 [-0.03407231  0.18523622  1.61762273  1.85349993]
 [-0.02579709  0.22383503  1.85349955  3.69523117]]
model -- 1 new_Q: 
[[ 1.87213722  2.17169734 -0.03419034 -0.02586525]
 [ 2.17169838  4.34950672  0.1851723   0.22374159]
 [-0.03407231  0.18523623  1.61762275  1.85349993]
 [-0.025

-1702.778921136145
model -- 0 new_A: 
[[ 1.00049841e+00  9.31858230e-01  6.53442065e-04 -4.59437410e-02]
 [ 2.00991241e-04  9.65464809e-01  4.73430387e-04 -3.97591463e-02]
 [-2.63563735e-04 -2.87223472e-02  1.00030903e+00  9.32922050e-01]
 [-2.74571511e-04 -2.63016386e-03 -3.76676766e-05  9.81844536e-01]]
model -- 1 new_A: 
[[ 1.00049841e+00  9.31858230e-01  6.53442059e-04 -4.59437428e-02]
 [ 2.00991208e-04  9.65464809e-01  4.73430381e-04 -3.97591479e-02]
 [-2.63563720e-04 -2.87223472e-02  1.00030903e+00  9.32922051e-01]
 [-2.74571498e-04 -2.63016399e-03 -3.76676741e-05  9.81844537e-01]]
model -- 0 new_Q: 
[[ 1.87513442  2.17038971 -0.0345512  -0.02558556]
 [ 2.17039082  4.34854297  0.18578491  0.22484246]
 [-0.03443267  0.18584902  1.6203046   1.85284284]
 [-0.02551718  0.22493543  1.85284242  3.69468293]]
model -- 1 new_Q: 
[[ 1.87513441  2.1703897  -0.03455119 -0.02558556]
 [ 2.1703908   4.34854296  0.18578491  0.22484246]
 [-0.03443265  0.18584902  1.62030457  1.85284284]
 [-0.0255

-1702.7804549052667
model -- 0 new_A: 
[[ 1.00049977e+00  9.31697425e-01  6.54765219e-04 -4.60196605e-02]
 [ 2.00801393e-04  9.65482670e-01  4.73297563e-04 -3.97554729e-02]
 [-2.63963989e-04 -2.87923962e-02  1.00030993e+00  9.32759459e-01]
 [-2.74578443e-04 -2.62294098e-03 -3.77603383e-05  9.81856974e-01]]
model -- 1 new_A: 
[[ 1.00049977e+00  9.31697425e-01  6.54765214e-04 -4.60196623e-02]
 [ 2.00801373e-04  9.65482670e-01  4.73297560e-04 -3.97554740e-02]
 [-2.63963970e-04 -2.87923962e-02  1.00030993e+00  9.32759460e-01]
 [-2.74578428e-04 -2.62294125e-03 -3.77603376e-05  9.81856976e-01]]
model -- 0 new_Q: 
[[ 1.87810892  2.16908252 -0.03491022 -0.02530325]
 [ 2.16908369  4.34760076  0.18639967  0.22594631]
 [-0.03479117  0.18646398  1.62296799  1.85218659]
 [-0.02523465  0.22603881  1.85218614  3.6941513 ]]
model -- 1 new_Q: 
[[ 1.87810896  2.16908253 -0.03491026 -0.02530327]
 [ 2.1690837   4.34760078  0.18639966  0.22594629]
 [-0.03479122  0.18646397  1.62296803  1.85218661]
 [-0.025

-1702.7820193522352
model -- 0 new_A: 
[[ 1.00050113e+00  9.31535875e-01  6.56094370e-04 -4.60958696e-02]
 [ 2.00612370e-04  9.65500434e-01  4.73165531e-04 -3.97518415e-02]
 [-2.64366559e-04 -2.88626635e-02  1.00031083e+00  9.32596218e-01]
 [-2.74585580e-04 -2.61577870e-03 -3.78522843e-05  9.81869293e-01]]
model -- 1 new_A: 
[[ 1.00050113e+00  9.31535875e-01  6.56094355e-04 -4.60958755e-02]
 [ 2.00612299e-04  9.65500435e-01  4.73165519e-04 -3.97518458e-02]
 [-2.64366495e-04 -2.88626636e-02  1.00031083e+00  9.32596223e-01]
 [-2.74585528e-04 -2.61577935e-03 -3.78522871e-05  9.81869297e-01]]
model -- 0 new_Q: 
[[ 1.8810607   2.16777585 -0.03526735 -0.02501837]
 [ 2.16777709  4.3466801   0.1870165   0.22705298]
 [-0.03514773  0.18708102  1.62561298  1.85153124]
 [-0.02494953  0.22714507  1.85153076  3.6936363 ]]
model -- 1 new_Q: 
[[ 1.88106075  2.16777586 -0.03526738 -0.02501841]
 [ 2.16777709  4.34668011  0.18701648  0.22705294]
 [-0.03514778  0.187081    1.62561305  1.85153129]
 [-0.024

-1702.783613439246
model -- 0 new_A: 
[[ 1.00050251e+00  9.31373584e-01  6.57429473e-04 -4.61723664e-02]
 [ 2.00424154e-04  9.65518101e-01  4.73034288e-04 -3.97482533e-02]
 [-2.64771414e-04 -2.89331475e-02  1.00031173e+00  9.32432333e-01]
 [-2.74592897e-04 -2.60867649e-03 -3.79435287e-05  9.81881495e-01]]
model -- 1 new_A: 
[[ 1.00050251e+00  9.31373585e-01  6.57429449e-04 -4.61723745e-02]
 [ 2.00424043e-04  9.65518102e-01  4.73034268e-04 -3.97482595e-02]
 [-2.64771330e-04 -2.89331477e-02  1.00031173e+00  9.32432340e-01]
 [-2.74592829e-04 -2.60867734e-03 -3.79435287e-05  9.81881500e-01]]
model -- 0 new_Q: 
[[ 1.88398964  2.16646978 -0.03562229 -0.02473086]
 [ 2.16647107  4.34578096  0.18763548  0.22816258]
 [-0.03550227  0.18770014  1.62823939  1.85087662]
 [-0.02466185  0.22825418  1.85087611  3.6931376 ]]
model -- 1 new_Q: 
[[ 1.8839897   2.16646977 -0.03562236 -0.0247309 ]
 [ 2.16647106  4.34578095  0.18763546  0.22816254]
 [-0.03550233  0.18770011  1.62823944  1.85087666]
 [-0.0246

-1702.785237033894
model -- 0 new_A: 
[[ 1.00050389e+00  9.31210556e-01  6.58770488e-04 -4.62491483e-02]
 [ 2.00236749e-04  9.65535671e-01  4.72903832e-04 -3.97447076e-02]
 [-2.65178551e-04 -2.90038462e-02  1.00031263e+00  9.32267809e-01]
 [-2.74600417e-04 -2.60163337e-03 -3.80340713e-05  9.81893579e-01]]
model -- 1 new_A: 
[[ 1.00050389e+00  9.31210558e-01  6.58770461e-04 -4.62491574e-02]
 [ 2.00236632e-04  9.65535672e-01  4.72903811e-04 -3.97447141e-02]
 [-2.65178456e-04 -2.90038464e-02  1.00031263e+00  9.32267816e-01]
 [-2.74600342e-04 -2.60163434e-03 -3.80340721e-05  9.81893585e-01]]
model -- 0 new_Q: 
[[ 1.88689574  2.16516439 -0.03597517 -0.02444087]
 [ 2.16516574  4.3449034   0.18825642  0.22927485]
 [-0.03585464  0.18832126  1.6308473   1.85022288]
 [-0.02437165  0.22936597  1.85022233  3.69265542]]
model -- 1 new_Q: 
[[ 1.88689583  2.1651644  -0.03597525 -0.02444092]
 [ 2.16516576  4.34490341  0.18825639  0.2292748 ]
 [-0.03585473  0.18832122  1.63084738  1.85022294]
 [-0.0243

-1702.78688941717
model -- 0 new_A: 
[[ 1.00050527e+00  9.31046797e-01  6.60117377e-04 -4.63262127e-02]
 [ 2.00050168e-04  9.65553143e-01  4.72774162e-04 -3.97412032e-02]
 [-2.65587956e-04 -2.90747577e-02  1.00031354e+00  9.32102649e-01]
 [-2.74608128e-04 -2.59464990e-03 -3.81239119e-05  9.81905545e-01]]
model -- 1 new_A: 
[[ 1.00050527e+00  9.31046799e-01  6.60117346e-04 -4.63262213e-02]
 [ 2.00050026e-04  9.65553145e-01  4.72774133e-04 -3.97412103e-02]
 [-2.65587872e-04 -2.90747575e-02  1.00031354e+00  9.32102656e-01]
 [-2.74608060e-04 -2.59465046e-03 -3.81239111e-05  9.81905551e-01]]
model -- 0 new_Q: 
[[ 1.88977898  2.16385976 -0.03632578 -0.02414838]
 [ 2.16386118  4.3440474   0.18887937  0.23038978]
 [-0.03620476  0.18894439  1.63343667  1.84957001]
 [-0.02407895  0.23048044  1.84956942  3.69218967]]
model -- 1 new_Q: 
[[ 1.88977902  2.16385974 -0.03632582 -0.02414841]
 [ 2.16386116  4.34404737  0.18887936  0.23038976]
 [-0.0362048   0.18894438  1.63343674  1.84957005]
 [-0.02407

-1702.7885699831477
model -- 0 new_A: 
[[ 1.00050667e+00  9.30882311e-01  6.61470107e-04 -4.64035574e-02]
 [ 1.99864400e-04  9.65570518e-01  4.72645272e-04 -3.97377400e-02]
 [-2.65999644e-04 -2.91458783e-02  1.00031445e+00  9.31936859e-01]
 [-2.74616054e-04 -2.58772358e-03 -3.82130692e-05  9.81917396e-01]]
model -- 1 new_A: 
[[ 1.00050667e+00  9.30882313e-01  6.61470075e-04 -4.64035676e-02]
 [ 1.99864264e-04  9.65570520e-01  4.72645247e-04 -3.97377474e-02]
 [-2.65999537e-04 -2.91458784e-02  1.00031445e+00  9.31936867e-01]
 [-2.74615969e-04 -2.58772474e-03 -3.82130684e-05  9.81917403e-01]]
model -- 0 new_Q: 
[[ 1.89263933  2.16255592 -0.03667413 -0.02385341]
 [ 2.16255741  4.34321289  0.18950423  0.23150728]
 [-0.03655258  0.18956943  1.63600769  1.84891795]
 [-0.02378376  0.23159746  1.84891734  3.69174022]]
model -- 1 new_Q: 
[[ 1.89263941  2.16255593 -0.03667421 -0.02385346]
 [ 2.16255741  4.3432129   0.18950419  0.23150722]
 [-0.03655267  0.18956939  1.63600777  1.84891803]
 [-0.023

Filter model. Testing with learnt parameters from EMGPB2.

In [8]:
em_transition_model_1 = LinearGaussianTimeInvariantTransitionModel(transition_matrix=new_models[0].A,
                                                                   covariance_matrix=new_models[0].Q)
em_transition_model_2 = LinearGaussianTimeInvariantTransitionModel(transition_matrix=new_models[1].A,
                                                                   covariance_matrix=new_models[1].Q)
em_measurement_noise_1 = new_models[0].R
em_measurement_noise_2 = new_models[1].R

em_measurement_model_1 = LinearGaussian(ndim_state=4, mapping=[0, 2],
                                   noise_covar=em_measurement_noise_1)
em_measurement_model_2 = LinearGaussian(ndim_state=4, mapping=[0, 2],
                                   noise_covar=em_measurement_noise_2)

em_model_transition_matrix = np.array([[0.5, 0.5],
                                       [0.5, 0.5]])
em_predictor_1 = KalmanPredictor(em_transition_model_1)
em_predictor_2 = KalmanPredictor(em_transition_model_2)
em_imm_predictor = IMMPredictor([em_predictor_1, em_predictor_2], em_model_transition_matrix)

em_updater_1 = KalmanUpdater(em_measurement_model_1)
em_updater_2 = KalmanUpdater(em_measurement_model_2)
em_imm_updater = IMMUpdater([em_updater_1, em_updater_2], em_model_transition_matrix)

em_state_init = WeightedGaussianState(StateVector([[0], [0], [0], [0]]),
                                      CovarianceMatrix(np.diag([5.0, 5.0, 5.0, 5.0])),
                                      timestamp=timestamp_init,
                                      weight=0.5)

prior = GaussianMixtureState([copy(em_state_init), copy(em_state_init)])
track = Track([copy(prior)])
track_error = []

for i in range(1, len(detection_track)-1):
    # measurement
    measurement = detection_track[i]
    # State prediction
    prediction = em_imm_predictor.predict(track.state, timestamp=gt_time[i])
    # Measurement prediction
    meas_prediction = em_imm_updater.predict_measurement(prediction)
    # Association
    hyp = SingleHypothesis(prediction, measurement)
    # State update
    prior = em_imm_updater.update(hyp)
    track.append(prior)
    track_error.append(em_measurement_model_1.function(track[i].state_vector, np.zeros((2,1))) - em_measurement_model_1.function(gt_track[i].state_vector, np.zeros((2,1))))

track_error = np.asarray(track_error)
track_error = np.squeeze(track_error)
rmse_tmp = []
for track_error_ in track_error:
    rmse_tmp.append(track_error_ @ track_error_.T)
rmse = np.sqrt(np.mean(np.array(rmse_tmp)))
print("RMSE: " + str(rmse))

RMSE: 0.5783371153888026
